services:
  prometheus:
    image: prom/prometheus:v2.45.0
    container_name: vinntry-prometheus
    volumes:
      - ./config/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    ports:
      - "9090:9090"
    extra_hosts:
      - "host.docker.internal:host-gateway" # Allows container to route to host port 8000
    restart: unless-stopped
    networks:
      - vinntry-net

  grafana:
    image: grafana/grafana:10.0.0
    container_name: vinntry-grafana
    ports:
      - "3000:3000"
    volumes:
      - ./config/grafana/datasources:/etc/grafana/provisioning/datasources # Auto-loads datasource
      - ./config/grafana/dashboards:/etc/grafana/provisioning/dashboards # Auto-loads dashboards
      - ./config/grafana/grafana.ini:/etc/grafana/grafana.ini
      - ./data:/data
      - grafana_data:/var/lib/grafana   

    environment:
      - GF_SECURITY_ADMIN_PASSWORD=vinntry_pass
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_DASHBOARDS_MIN_REFRESH_INTERVAL=100ms
      - GF_INSTALL_PLUGINS=frser-sqlite-datasource
    networks:
      - vinntry-net

volumes:
  prometheus_data:
  grafana_data:

networks:
  vinntry-net:
    driver: bridge