[dashboards]
# Force Grafana to use your custom provisioned dashboard as the root landing page
default_home_dashboard_path = /etc/grafana/provisioning/dashboards/vinntry-dash.json

[users]
# System-wide landing page override. Bypasses the default home layout 
# and drops the user directly into your provisioned dashboard list view.
home_page = /dashboards?search=open
