apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090 # Internal docker network routing to TSDB container
    isDefault: true
    editable: false